gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff9e3b"
      - "bold"
    unstagedChangesColor:
      - "#e82424"
    selectedLineBgColor:
      - "#223249"
    searchingActiveBorderColor:
      - "#ff9e3b"
      - "bold"
    optionsTextColor:
      - "#7e9cd8"
    inactiveBorderColor:
      - "#54546d"
    defaultFgColor:
      - "#dcd7ba"
    cherryPickedCommitFgColor:
      - "#7e9cd8"
    cherryPickedCommitBgColor:
      - "#e6c384"
os:
  editPreset: "nvim-remote"
