# BACKGROUND
background {
    monitor =
    #path = screenshot
    path = /home/rishavc/Pictures/Wallpapers/blade-runner.jpg
    #color = $background
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    hide_cursor = true
    ignore_empty_input = true
    grace = 0
    fail_timeout = 1200
}

# INPUT FIELD
input-field {
    size = 120, 120
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgb(31, 31, 40)
    outer_color = rgb(84, 84, 109)
    font_color = rgb(220, 215, 186)
    font_family = "Iosevka"
    fade_on_empty = false
    check_color = rgb(220, 165, 97)
    fail_color = rgb(195, 64, 67)
    placeholder_text = <i>Input Password</i>
    hide_input = true
    hide_input_base_color = rgb(126, 156, 216)
    position = 0, -200
    rounding = 0
    halign = center
    valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}
